FROM golang:1.22-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o gateway .

FROM alpine:latest

WORKDIR /app
COPY --from=build /app/gateway .

EXPOSE 8000

CMD ["./gateway"]